name: 'Dependabot Action'
description: 'Runs Dependabot as an action, this is needed e.g. for GH Enterprise'
author: 'paschdan'
inputs:
  token: # change this
    required: true
    description: 'Personal access token (PAT) of GHE'
    default: '${{ github.token }}'
  github_token:
    required: false
    description: 'Personal access token for github.com to overcome request limits'
  package_manager:
    required: true
    description: 'package manager for dependabot, available values: terraform,python,dep,go_modules,hex,composer,npm_and_yarn'

runs:
  using: docker
  image: docker://ghcr.io/paschdan/semantic-pullrequest-action:v1
